observation:
  command:
    ref_root_pos_future_local:
      _target_: mimic_lite.ref_body_pos_future_local
      body_names: pelvis
      future_steps:
      - -8
      - -4
      - -2
      - 0
      - 1
      - 2
      - 3
      - 4
      noise_std: 0.005
    ref_root_ori_future_b:
      _target_: mimic_lite.ref_root_ori_future_b
      future_steps:
      - -8
      - -4
      - -2
      - 0
      - 1
      - 2
      - 3
      - 4
      noise_std: 0.05
    ref_joint_pos_future:
      _target_: mimic_lite.ref_joint_pos_future
      future_steps:
      - -8
      - -4
      - -2
      - 0
      - 1
      - 2
      - 3
      - 4
      noise_std: 0.0
  policy:
    root_ang_vel_history:
      _target_: mimic_lite.root_ang_vel_history
      history_steps:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 8
      - 16
      noise_std: 0.2
    projected_gravity_history:
      _target_: mimic_lite.projected_gravity_history
      history_steps:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 8
      - 16
      noise_std: 0.01
    joint_pos_history:
      _target_: mimic_lite.joint_pos_history
      history_steps:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 8
      - 16
      noise_std: 0.02
    joint_vel_history:
      _target_: mimic_lite.joint_vel_history
      history_steps:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 8
      - 16
      noise_std: 0.5
    prev_actions:
      _target_: mimic_lite.prev_actions
      steps: 3
joint_names_simulation:
- left_hip_pitch_joint
- right_hip_pitch_joint
- waist_yaw_joint
- left_hip_roll_joint
- right_hip_roll_joint
- waist_roll_joint
- left_hip_yaw_joint
- right_hip_yaw_joint
- waist_pitch_joint
- left_knee_joint
- right_knee_joint
- left_shoulder_pitch_joint
- right_shoulder_pitch_joint
- left_ankle_pitch_joint
- right_ankle_pitch_joint
- left_shoulder_roll_joint
- right_shoulder_roll_joint
- left_ankle_roll_joint
- right_ankle_roll_joint
- left_shoulder_yaw_joint
- right_shoulder_yaw_joint
- left_elbow_joint
- right_elbow_joint
- left_wrist_roll_joint
- right_wrist_roll_joint
- left_wrist_pitch_joint
- right_wrist_pitch_joint
- left_wrist_yaw_joint
- right_wrist_yaw_joint
body_names_simulation:
- pelvis
- left_hip_pitch_link
- right_hip_pitch_link
- waist_yaw_link
- left_hip_roll_link
- right_hip_roll_link
- waist_roll_link
- left_hip_yaw_link
- right_hip_yaw_link
- torso_link
- left_knee_link
- right_knee_link
- left_shoulder_pitch_link
- right_shoulder_pitch_link
- left_ankle_pitch_link
- right_ankle_pitch_link
- left_shoulder_roll_link
- right_shoulder_roll_link
- left_ankle_roll_link
- left_toe_link
- right_ankle_roll_link
- right_toe_link
- left_shoulder_yaw_link
- right_shoulder_yaw_link
- left_elbow_link
- right_elbow_link
- left_wrist_roll_link
- right_wrist_roll_link
- left_wrist_pitch_link
- right_wrist_pitch_link
- left_wrist_yaw_link
- right_wrist_yaw_link
joint_kp:
  .*_elbow_joint|.*_shoulder_pitch_joint|.*_shoulder_roll_joint|.*_shoulder_yaw_joint|.*_wrist_roll_joint: 14.25062309787429
  .*_hip_pitch_joint: 99.09842777666111
  .*_hip_yaw_joint|waist_yaw_joint: 40.17923863450712
  .*_hip_roll_joint|.*_knee_joint: 99.09842777666111
  .*_wrist_pitch_joint|.*_wrist_yaw_joint: 8.611032447370201
  waist_pitch_joint|waist_roll_joint: 28.50124619574858
  .*_ankle_pitch_joint|.*_ankle_roll_joint: 28.50124619574858
joint_kd:
  .*_elbow_joint|.*_shoulder_pitch_joint|.*_shoulder_roll_joint|.*_shoulder_yaw_joint|.*_wrist_roll_joint: 0.907222843292423
  .*_hip_pitch_joint: 6.308801853496639
  .*_hip_yaw_joint|waist_yaw_joint: 2.557889775413375
  .*_hip_roll_joint|.*_knee_joint: 6.308801853496639
  .*_wrist_pitch_joint|.*_wrist_yaw_joint: 0.548195351665136
  waist_pitch_joint|waist_roll_joint: 1.814445686584846
  .*_ankle_pitch_joint|.*_ankle_roll_joint: 1.814445686584846
default_joint_pos:
  .*_hip_pitch_joint: -0.312
  .*_knee_joint: 0.669
  .*_ankle_pitch_joint: -0.363
  .*_elbow_joint: 0.6
  left_shoulder_roll_joint: 0.2
  left_shoulder_pitch_joint: 0.2
  right_shoulder_roll_joint: -0.2
  right_shoulder_pitch_joint: 0.2
policy_joint_names:
- left_hip_pitch_joint
- right_hip_pitch_joint
- waist_yaw_joint
- left_hip_roll_joint
- right_hip_roll_joint
- waist_roll_joint
- left_hip_yaw_joint
- right_hip_yaw_joint
- waist_pitch_joint
- left_knee_joint
- right_knee_joint
- left_shoulder_pitch_joint
- right_shoulder_pitch_joint
- left_ankle_pitch_joint
- right_ankle_pitch_joint
- left_shoulder_roll_joint
- right_shoulder_roll_joint
- left_ankle_roll_joint
- right_ankle_roll_joint
- left_shoulder_yaw_joint
- right_shoulder_yaw_joint
- left_elbow_joint
- right_elbow_joint
- left_wrist_roll_joint
- right_wrist_roll_joint
- left_wrist_pitch_joint
- right_wrist_pitch_joint
- left_wrist_yaw_joint
- right_wrist_yaw_joint
action_scale:
- 0.550000011920929
- 0.550000011920929
- 0.550000011920929
- 0.3499999940395355
- 0.3499999940395355
- 0.4399999976158142
- 0.550000011920929
- 0.550000011920929
- 0.4399999976158142
- 0.3499999940395355
- 0.3499999940395355
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
- 0.4399999976158142
motion:
  motion_cfgs:
    lafan:
      path: ../any4hdmi/output/g1/lafan
      weight: 1.0
      full_motion: true
      shard: false
  motion_path: ../any4hdmi/output/g1/lafan
  future_steps:
  - -8
  - -4
  - -2
  - 0
  - 1
  - 2
  - 3
  - 4
  body_names:
  - pelvis
  - left_hip_yaw_link
  - right_hip_yaw_link
  - torso_link
  - left_knee_link
  - right_knee_link
  - left_toe_link
  - right_toe_link
  - left_shoulder_yaw_link
  - right_shoulder_yaw_link
  - left_elbow_link
  - right_elbow_link
  - left_wrist_yaw_link
  - right_wrist_yaw_link
  joint_names:
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - waist_yaw_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - waist_roll_joint
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - waist_pitch_joint
  - left_knee_joint
  - right_knee_joint
  - left_shoulder_pitch_joint
  - right_shoulder_pitch_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_shoulder_roll_joint
  - right_shoulder_roll_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
  - left_shoulder_yaw_joint
  - right_shoulder_yaw_joint
  - left_elbow_joint
  - right_elbow_joint
  - left_wrist_roll_joint
  - right_wrist_roll_joint
  - left_wrist_pitch_joint
  - right_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_wrist_yaw_joint
  root_body_name: pelvis
  anchor_body_name: pelvis
